[package]
name = "pipey"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
futures-util = "0.3.31"
redis = { version = "0.27.5", features = ["tokio-comp", "aio"] }
thiserror = "1.0.65"
tokio = { version = "1.41.0", features = ["full"] }
